### ISSUE TITLE
Why does Manjaro have Ubuntu in /etc/os-release

### ISSUE THREAD

**Issue by ziacik** [manjaro/issues-hub#13]
How could this possibly happen?

![image](https://github.com/user-attachments/assets/6f1df164-ba5d-4bc5-8f9e-a1b0e1f8eefb)

**Comment by cfinnberg** [comment]
Something you have installed from AUR? I don't have that. You also have Ubuntu logo in your prompt...

**Comment by ziacik** [comment]
> Something you have installed from AUR? I don't have that. You also have Ubuntu logo in your prompt...

Right... Probably something on my side. Thanks
