### ISSUE TITLE
After login my desktop Icons are not shown if the preference “Show preview thumbnails” is disabled

### ISSUE THREAD

**Issue by seniordevel** [manjaro/issues-hub#14]
After login my desktop Icons are not shown if the preference “Show preview thumbnails” is disabled. Only the default icon placeholders are shown. However, icons will load either on mouse-click or selecting a icon desktop area with a rectangle. First I tried to clear the icon cache, but still the same issue after login. This never happened before the latest update.

**To Reproduce**
Install latest big update:
1. In Manjaro set  preference “Show preview thumbnails” to disabled
2. Reboot
3. See desktop icons not loaded

**Expected behavior**
Desktop icons should be shown, even if preference “Show preview thumbnails” was disabled in last session

**Environment:**
`Operating System: Manjaro Linux 
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.1
Kernel Version: 6.11.10-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G
Memory: 14,6 GiB of RAM
Graphics Processor: KAVERI`

**Comment by romangg** [comment]
Looks to me like an upstream issue in KDE :arrow_right:  report at https://bugs.kde.org/
